GoogleCloudPlatform/cloud-run-samples

identity-platform/gke/README.md
identity-platform/gke/backend/.dockerignore
identity-platform/gke/backend/.gcloudignore
identity-platform/gke/backend/Dockerfile
identity-platform/gke/backend/app.py
identity-platform/gke/backend/requirements.txt
identity-platform/gke/frontend/.dockerignore
identity-platform/gke/frontend/.gcloudignore
identity-platform/gke/frontend/.gitignore
identity-platform/gke/frontend/Dockerfile
identity-platform/gke/frontend/app.py
identity-platform/gke/frontend/index.html
identity-platform/gke/frontend/index.template.js
identity-platform/gke/frontend/requirements.txt
identity-platform/gke/istio/authenticationpolicy.template.yaml
identity-platform/gke/istio/virtualservice.yaml

This sample accompanies the tutorial on
Authenticating Cloud Run on GKE end users using
Istio and Identity Platform.

Add sample for end user authentication tutorial

---

CODEOWNERS
README.md
get-external-ip.sh
istio-authorization/.gitignore
istio-authorization/README.md
istio-authorization/authenticationpolicy.template.yaml
istio-authorization/clusterrbacconfig.yaml
istio-authorization/id_token_request.py
istio-authorization/requirements.txt
istio-authorization/servicerole.yaml
istio-authorization/servicerolebinding.template.yaml

This sample uses Istio's authentication and authorization features.

Add Cloud Run on GKE authorization sample code

---

istio-authorization/README.md
istio-authorization/authenticationpolicy.yaml
istio-authorization/get-external-ip.sh
istio-authorization/id_token_request.py
istio-authorization/requirements.txt
istio-authorization/servicerolebinding.template.yaml

The main change is the new name and namespace for the Istio ingress
gateway.

Updates for the GA release of Cloud Run for Anthos

---

helloworld-shell/tests.cloudbuild.yaml

Reverts GoogleCloudPlatform/cloud-run-samples#77
Fixes #78

Revert "test: intentional break to test flake bot"

---

testing/test-cases/Dockerfile

This region tag is in conflict, but also isn't needed in this repo.

Remove region tag from test case

---

testing/flakybot-function/deploy_function.sh

Bump version from Python 3.7 to Python 3.8

testing(flakybot): update to Python 3.8

---

helloworld-shell/Dockerfile
identity-platform/gke/backend/Dockerfile
identity-platform/gke/frontend/Dockerfile

**N.B:** I have **not** tested this locally.

fix(helloworld-shell): fix hadolint

---

jobs-shell/tests.cloudbuild.yaml
jobs-shell/tests/e2e-cleanup.sh

Clean up resources and tag image

---

gcloud-report/script.sh
gcloud-report/tests.cloudbuild.yaml
helloworld-shell/tests.cloudbuild.yaml
testing/cloudbuild-templates/cloud-run-anthos-template.cloudbuild.yaml
testing/cloudbuild-templates/cloud-run-template.cloudbuild.yaml
testing/cloudbuild-templates/common.sh
vpc-sample/README.md
vpc-sample/tests.cloudbuild.yaml

chore: Update to use build id

---

testing/cloudbuild-templates/common.sh
testing/cloudbuild-templates/retry.sh

**Issue:** #68 Moves akitsch@ 's gcloud retry script for sample testing usage.

chore(issue-68): importing sample testing retry script

---

volume-checker/Dockerfile
volume-checker/go.mod
volume-checker/main.go
volume-checker/main_test.go
volume-checker/tests.cloudbuild.yaml

the cloud run volume checker makes it easier for volumes users to check that their cloud run deployment has connectivity to the volume source, and that the volume contents are present in the running container once mounted.

add volume-checker sample

---

vpc-sample/Dockerfile
vpc-sample/README.md
vpc-sample/tests.cloudbuild.yaml

The main change is 403 -> 404. Referencing https://cloud.google.com/functions/docs/networking/network-settings
All other changes are formatting.

fix: update Cloud Build test config for VPC sample

---

vpc-sample/tests.cloudbuild.yaml

fix: reduce flakiness of vpc sample

---

vpc-sample/tests.cloudbuild.yaml

chore: reduce flakiness of VPC sample test

---

multi-container/hello-nginx-sample/service.yaml

**Issue:** shifting region tag up to include `spec/container` lines

chore: update region tag for sidecar tutorial

---

vpc-sample/tests.cloudbuild.yaml

**Issue:** #200 
Further explanation within b/293761696.

fix(issue-200): resolve flaky unknown blob failure after container image push 

---

README.md

chore: update readme samples

---

multi-container/hello-nginx-sample/service.yaml

fix: swap container deps in run mc sample, adding healthchecks

---

jobs-shell/README.md
jobs-shell/tests/e2e-cleanup.sh
jobs-shell/tests/e2e-test.sh

chore(b-230113499): remove alpha references from jobs

---

gcloud-report/tests.cloudbuild.yaml
helloworld-shell/tests.cloudbuild.yaml
jobs-shell/README.md
jobs-shell/tests.cloudbuild.yaml
jobs-shell/tests/e2e-cleanup.sh
jobs-shell/tests/e2e-test.sh
multi-container/hello-nginx-sample/tests.cloudbuild.yaml
testing/cloudbuild-templates/cloud-run-anthos-template.cloudbuild.yaml
testing/cloudbuild-templates/cloud-run-template.cloudbuild.yaml
vpc-sample/README.md
vpc-sample/tests.cloudbuild.yaml

* Update all built images to Artifact Registry
* Replaces Docker Cloud Builder with cloud-sdk image
* Updates any related README.md docs. 
Resolves #268, #263, #264

feat: migrate to Artifact Registry

---

CODEOWNERS

Requires repo settings config from @grayside before CODEOWNERS will validate

chore: update CODEOWNERs to team-egg
